---
- name: Ensure we know about kernel version
  when:
    - ansible_facts['kernel'] is undefined
  ansible.builtin.setup:
    gather_subset:
      - '!all,!min'
      - 'kernel'

- name: Ensure kpatch package is installed
  become: true
  ansible.builtin.package:
    name: kpatch
    state: present

- name: Install kpatch-patch if available  # noqa: package-latest
  failed_when: false
  become: true
  ansible.builtin.package:
    name: "kpatch-patch = {{ ansible_facts['kernel'] }}"
    state: latest

- name: Ensure further update stages will not update kernel
  vars:
    _kernel:
      - kernel
      - kernel-core
  ansible.builtin.set_fact:
    _exclude_packages: "{{ edpm_update_exclude_packages + _kernel }}"
