---
- hosts: all
  tasks:
    - name: Get git tag for image tagging
      register: edpm_ansible_tag
      ansible.builtin.command:
        cmd: git show-ref --head --hash head
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/edpm-ansible"

    - name: Set openstack-runner image
      ansible.builtin.set_fact:
        ansibleee_runner_img: "quay.rdoproject.org/openstack-k8s-operators/openstack-ansibleee-runner:{{ edpm_ansible_tag.stdout|trim }}"

    - name: Build openstack-runner image
      community.general.make:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/edpm-ansible"
        target: openstack_ansibleee_build
        params:
          IMG: "{{ ansibleee_runner_img }}"

    - name: Push openstack-runner image
      community.general.make:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/edpm-ansible"
        target: openstack_ansibleee_push
        params:
          IMG: "{{ ansibleee_runner_img }}"

    - name: Set make_edpm_deploy_env var
      ansible.builtin.set_fact:
        make_edpm_deploy_env: {'DATAPLANE_RUNNER_IMG': "{{ ansibleee_runner_img }}"}
        cacheable: true
