---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
- name: Prepare test_deps
  hosts: all
  gather_facts: false
  roles:
    - role: ../../../../molecule/common/test_deps
      test_deps_extra_packages:
        - podman
- name: Prepare
  hosts: all
  gather_facts: false
  roles:
    - role: osp.edpm.env_data
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Create config-data telemetry directory
      ansible.builtin.file:
        path: "{{ edpm_telemetry_config_src }}"
        state: directory
        mode: "0775"

    - name: set /etc/localtime
      become: true
      ansible.builtin.file:
        path: /etc/localtime
        src: /usr/share/zoneinfo/UTC
        state: link

    - name: Create /run/libvirt directory
      ansible.builtin.file:
        path: "/run/libvirt"
        state: directory
        mode: "0775"

    - name: Create libvirt user
      command: groupadd libvirt

    - name: Create firewall directory
      become: true
      ansible.builtin.file:
        path: "/var/lib/edpm-config/firewall"
        state: directory
        owner: root
        group: root
        mode: 0750

    - name: Create ceilometer.conf
      ansible.builtin.copy:
        dest: "{{ edpm_telemetry_config_src }}/ceilometer.conf"
        mode: "0644"
        owner: root
        group: root
        content: |
          [DEFAULT]
          tenant_name_discovery=False
          debug=True
          log_dir=/var/log/ceilometer
          rpc_response_timeout=60
          polling_namespaces=compute

          [service_credentials]
          auth_type=password
          auth_url=http://keystone-internal.openstack.svc:5000
          project_name=service
          project_domain_name=Default
          username=ceilometer
          user_domain_name=Default

          [compute]
          instance_discovery_method=libvirt_metadata

          [coordination]
          backend_url=

          [publisher]
          telemetry_secret=eQ5qb0yysfJ8lx82Vl061vSyY

    - name: Create polling.yaml
      ansible.builtin.copy:
        dest: "{{ edpm_telemetry_config_src }}/polling.yaml"
        mode: "0644"
        owner: root
        group: root
        content: |
          ---
          sources:
              - name: some_pollsters
                interval: 300
                meters:
                  - cpu
                  - disk.*
                  - ip.*
                  - image.*
                  - memory
                  - memory.*
                  - network.*
                  - perf.*
                  - port
                  - port.*
                  - switch
                  - switch.*
                  - storage.*
                  - volume.*
                  - hardware.*

    - name: Install crypto dependency
      become: true
      ansible.builtin.dnf:
        name: python3-cryptography
        state: present

    - name: Create certs directory
      ansible.builtin.file:
        path: "{{ edpm_telemetry_certs }}"
        state: directory
        mode: "0775"

    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      community.crypto.openssl_privatekey:
        path: "{{ edpm_telemetry_certs }}/tls.key"
        mode: "0600"
        owner: root
        group: root

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: "{{ edpm_telemetry_certs }}/tls.crt"
        privatekey_path: "{{ edpm_telemetry_certs }}/tls.key"
        provider: selfsigned
        mode: "0600"
        owner: root
        group: root
