---
- name: Converge
  hosts: all
  tasks:
    - name: Converge
      block:
        - name: "Include role"
          ansible.builtin.include_role:
            name: osp.edpm.edpm_pre_adoption_validation
