---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if unit file exists and fail if it does
      ansible.builtin.file:
        path: /usr/lib/systemd/system/fake-tripleo-service.service
        state: absent
      check_mode: true
